# Generated by Django 4.2.17 on 2025-01-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Покупатели', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
    ]
